/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as ShopSuccessRouteImport } from './routes/shop/success'
import { Route as ApiCheckoutSuccessRouteImport } from './routes/api/checkout.success'
import { Route as ApiCronEventRemindersRouteImport } from './routes/api/cron/event-reminders'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSuccessRoute = ShopSuccessRouteImport.update({
  id: '/shop/success',
  path: '/shop/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSuccessRoute = ApiCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApiCheckoutRoute,
} as any)
const ApiCronEventRemindersRoute = ApiCronEventRemindersRouteImport.update({
  id: '/api/cron/event-reminders',
  path: '/api/cron/event-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/evenements': typeof EvenementsRoute
  '/panier': typeof PanierRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/send-email': typeof ApiSendEmailRoute
  '/shop/success': typeof ShopSuccessRoute
  '/api/checkout/success': typeof ApiCheckoutSuccessRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/evenements': typeof EvenementsRoute
  '/panier': typeof PanierRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/send-email': typeof ApiSendEmailRoute
  '/shop/success': typeof ShopSuccessRoute
  '/api/checkout/success': typeof ApiCheckoutSuccessRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRoute
  '/evenements': typeof EvenementsRoute
  '/panier': typeof PanierRoute
  '/api/checkout': typeof ApiCheckoutRouteWithChildren
  '/api/send-email': typeof ApiSendEmailRoute
  '/shop/success': typeof ShopSuccessRoute
  '/api/checkout/success': typeof ApiCheckoutSuccessRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/evenements'
    | '/panier'
    | '/api/checkout'
    | '/api/send-email'
    | '/shop/success'
    | '/api/checkout/success'
    | '/api/cron/event-reminders'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/boutique'
    | '/evenements'
    | '/panier'
    | '/api/checkout'
    | '/api/send-email'
    | '/shop/success'
    | '/api/checkout/success'
    | '/api/cron/event-reminders'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/evenements'
    | '/panier'
    | '/api/checkout'
    | '/api/send-email'
    | '/shop/success'
    | '/api/checkout/success'
    | '/api/cron/event-reminders'
    | '/api/cron/reminders'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoutiqueRoute: typeof BoutiqueRoute
  EvenementsRoute: typeof EvenementsRoute
  PanierRoute: typeof PanierRoute
  ApiCheckoutRoute: typeof ApiCheckoutRouteWithChildren
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ShopSuccessRoute: typeof ShopSuccessRoute
  ApiCronEventRemindersRoute: typeof ApiCronEventRemindersRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/success': {
      id: '/shop/success'
      path: '/shop/success'
      fullPath: '/shop/success'
      preLoaderRoute: typeof ShopSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/success': {
      id: '/api/checkout/success'
      path: '/success'
      fullPath: '/api/checkout/success'
      preLoaderRoute: typeof ApiCheckoutSuccessRouteImport
      parentRoute: typeof ApiCheckoutRoute
    }
    '/api/cron/event-reminders': {
      id: '/api/cron/event-reminders'
      path: '/api/cron/event-reminders'
      fullPath: '/api/cron/event-reminders'
      preLoaderRoute: typeof ApiCronEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiCheckoutRouteChildren {
  ApiCheckoutSuccessRoute: typeof ApiCheckoutSuccessRoute
}

const ApiCheckoutRouteChildren: ApiCheckoutRouteChildren = {
  ApiCheckoutSuccessRoute: ApiCheckoutSuccessRoute,
}

const ApiCheckoutRouteWithChildren = ApiCheckoutRoute._addFileChildren(
  ApiCheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoutiqueRoute: BoutiqueRoute,
  EvenementsRoute: EvenementsRoute,
  PanierRoute: PanierRoute,
  ApiCheckoutRoute: ApiCheckoutRouteWithChildren,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ShopSuccessRoute: ShopSuccessRoute,
  ApiCronEventRemindersRoute: ApiCronEventRemindersRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
